async function authRequest(action,body){const response=await fetch('/api/auth/'+action,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Admin-Entry':location.pathname.replace(/\/$/,'')||'/'},body:body===undefined?undefined:JSON.stringify(body)});if(!response.ok){const err=new Error((await response.text()).trim()||'请求失败');err.status=response.status;throw err}return response.status===204?null:response.json()}
function showAuthPanel(panel){$('#authScreen').hidden=false;$('#shell').hidden=true;['authLoading','firstInstall','login'].forEach(id=>$('#'+id).hidden=id!==panel);document.body.classList.add('auth-visible');if(panel==='login'){$('#password').value='';$('#username').focus()}if(panel==='firstInstall')$('#setupUsername').focus()}
async function enterAdmin(entryPath){$('.auth-wordmark').href=entryPath||location.pathname;if(entryPath&&location.pathname!==entryPath){history.replaceState(null,'',entryPath)}await refresh();$('#authScreen').hidden=true;$('#shell').hidden=false;document.body.classList.remove('auth-visible');$('#password').value='';$('#setupForm').reset()}
async function initializeAuth(){$('.auth-wordmark').href=location.pathname;try{sessionStorage.removeItem('adminUsername');sessionStorage.removeItem('adminPassword')}catch(e){}showAuthPanel('authLoading');$('#authRetry').hidden=true;$('#authLoadMessage').textContent='连接你的 RemoteGate 服务器。';try{const status=await authRequest('status');if(!status.initialized){showAuthPanel('firstInstall');return}if(status.authenticated){await enterAdmin(status.entryPath);return}showAuthPanel('login')}catch(e){$('#authLoadMessage').textContent='无法读取安装状态：'+e.message;$('#authRetry').hidden=false}}
async function loginWithAccount(){const button=$('#loginSubmit');button.disabled=true;$('#loginerror').textContent='';try{const result=await authRequest('login',{username:$('#username').value.trim(),password:$('#password').value});await enterAdmin(result.entryPath)}catch(e){$('#loginerror').textContent=e.message}finally{button.disabled=false}}
async function logoutAccount(){try{await authRequest('logout',{});showAuthPanel('login')}catch(e){toast('退出失败：'+e.message)}}
$('#authRetry').onclick=()=>initializeAuth();
$('#setupShowPassword').onchange=e=>{const type=e.target.checked?'text':'password';$('#setupPassword').type=type;$('#setupConfirm').type=type};
$('#setupForm').onsubmit=async e=>{e.preventDefault();const password=$('#setupPassword').value,confirmPassword=$('#setupConfirm').value,button=$('#setupSubmit');$('#setupError').textContent='';if(password!==confirmPassword){$('#setupError').textContent='两次输入的密码不一致';$('#setupConfirm').focus();return}button.disabled=true;button.textContent='正在创建管理员…';try{const username=$('#setupUsername').value.trim();const result=await authRequest('setup',{username,password,confirmPassword,entryPath:$('#setupEntry').value.trim()});$('#setupForm').reset();$('#setupPassword').type='password';$('#setupConfirm').type='password';$('#username').value=username;await enterAdmin(result.entryPath);toast('安装完成，请收藏当前后台地址')}catch(err){if(err.status===409){showAuthPanel('login');$('#loginerror').textContent='管理员已创建，请使用已有账号登录'}else $('#setupError').textContent=err.message}finally{button.disabled=false;button.textContent='创建管理员并进入后台 →'}};

function updateSetupEntryPreview(){const value=$("#setupEntry").value.trim();$("#setupEntryPreview").textContent="安装后的后台地址："+location.origin+(value.startsWith("/")?value:"/"+value)}
$("#setupEntry").oninput=updateSetupEntryPreview;updateSetupEntryPreview();
