const providerInfo={manual:{name:'其他平台 / 手动管理'},alidns:{name:'阿里云 DNS',one:'AccessKey ID',two:'AccessKey Secret',hint:'使用能修改此域名 TXT 记录的 RAM 凭据。'},dnspod:{name:'腾讯云 DNSPod',one:'DNSPod ID,Token',hint:'使用 DNSPod API 的 ID,Token 组合，不是腾讯云 SecretId / SecretKey。'},cloudflare:{name:'Cloudflare',one:'DNS API Token',two:'Zone API Token（可选）',hint:'Token 需有此域名的 Zone:Read 和 DNS:Edit 权限；不使用 Global API Key。'}};
function certificatePath(d){return 'certificates?domainId='+encodeURIComponent(d.id)}
function certDate(v){return v&&!v.startsWith('0001')?new Date(v).toLocaleString():'—'}
async function renderCertificates(d){await loadDomainCertificate(d)}
function certificateNames(value){return [...new Set(value.split(/[\n,，]+/).map(v=>v.trim().toLowerCase()).filter(Boolean))]}
function certificateSourceLabel(source){return source==='acme'?'ACME 自动申请':source==='path'?'服务器路径':source==='upload'?'上传证书':'待申请'}
function certificateRenewalFields(c){return `<div class="cert-grid"><label>提前续期（天）<input name="renewBeforeDays" type="number" min="1" max="90" required value="${Number(c.renewBeforeDays)||30}"></label><label>失败重试间隔（小时）<input name="retryHours" type="number" min="1" max="168" required value="${Number(c.retryHours)||12}"></label></div><p class="cert-field-hint">每小时检查一次；续期失败继续使用有效的旧证书。若有效期短于提前天数，会在有效期经过约 2/3 后续期。</p>`}
function certificateGuide(d){return `<details class="cert-help" data-cert-guide><summary>填写指南 · 域名、凭据与 HTTPS</summary><div class="cert-guide-grid"><div><b>1. 选择来源</b><p>自动申请：DNS 验证签发与续期。上传证书：证书链和未加密私钥。服务器路径：服务端可访问的证书文件。</p></div><div><b>2. 确认覆盖范围</b><p><code>${esc(d.baseDomain)}</code> 与 <code>*.${esc(d.baseDomain)}</code> 可一起申请。泛域名覆盖下一层，如 <code>router.${esc(d.baseDomain)}</code>，不覆盖再下一层。</p></div><div><b>3. DNS 授权</b><p>选择实际负责解析的平台，与购买域名的平台可以不同。申请临时创建 TXT 验证记录；网站 A / AAAA 记录仍需配置。</p></div><div><b>4. HTTPS 入口</b><p>内置 HTTPS 按访问域名匹配证书，还需启用监听并放行端口。使用宝塔等外部代理时，需把证书配置到代理上。</p></div></div></details>`}
function openCertificateEditor(d,c={},requestedSource){
 const sourceDrafts=new Map();let activeSource='',submitting=false;
 let dialog=document.getElementById('certDialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='certDialog';dialog.className='cert-dialog';document.body.append(dialog)}
 dialog.innerHTML=`<form id="certificateEditor"><header class="cert-dialog-head"><div><span class="eyebrow">${esc(d.baseDomain)} · HTTPS</span><h2>${uiIcon('shield')}${c.installed?'管理证书':'添加证书'}</h2><p>先确认覆盖的域名，再选择申请或导入。</p></div><button type="button" class="icon-button" aria-label="关闭证书窗口">${uiIcon('close')}</button></header><div class="cert-dialog-body"><div class="cert-source-label"><b>证书来源</b><button type="button" data-cert-help>填写指南</button></div><div class="source-choices"><label><input type="radio" name="source" value="acme" checked><b>${uiIcon('shield')}自动申请</b><span>免费 ACME · 推荐</span></label><label><input type="radio" name="source" value="upload"><b>${uiIcon('upload')}上传证书</b><span>证书链 + 私钥</span></label><label><input type="radio" name="source" value="path"><b>${uiIcon('folder')}服务器路径</b><span>读取已有文件</span></label></div>${certificateGuide(d).replace('<details ', '<details hidden ')}<div id="certificateSourceFields"></div><p id="certificateError" class="cert-form-error" role="alert"></p></div><footer class="cert-dialog-foot"><span id="certificateProgress" role="status">保存配置后可稍后申请</span><button type="button" data-cert-cancel>取消</button><button type="submit" id="certificateSaveOnly" value="save">仅保存配置</button><button type="submit" class="primary" id="certificateSubmit">保存并申请</button></footer></form>`;
 const form=dialog.querySelector('form'),guide=dialog.querySelector('[data-cert-guide]');
 const close=()=>{if(!submitting){dialog.close();dialog.replaceChildren()}};
 dialog.querySelector('.icon-button').onclick=close;dialog.querySelector('[data-cert-cancel]').onclick=close;dialog.oncancel=e=>{e.preventDefault();close()};
 dialog.querySelector('[data-cert-help]').onclick=()=>{guide.hidden=!guide.hidden;guide.open=!guide.hidden;if(guide.open)guide.scrollIntoView({block:'nearest'})};
 form.querySelectorAll('[name=source]').forEach(r=>r.onchange=()=>sourceFields(r.value));
 function sourceFields(source){
  const box=dialog.querySelector('#certificateSourceFields');
  if(activeSource){const saved=document.createElement('div');while(box.firstChild)saved.append(box.firstChild);sourceDrafts.set(activeSource,saved)}activeSource=source;
  dialog.querySelector('#certificateSaveOnly').hidden=source!=='acme';dialog.querySelector('#certificateError').textContent='';
  dialog.querySelector('#certificateSubmit').textContent=source==='acme'?'保存并申请':source==='path'?'读取并安装':'校验并安装';
  dialog.querySelector('#certificateProgress').textContent=source==='acme'?'保存配置后可稍后申请':'校验通过后替换当前证书';
  if(sourceDrafts.has(source)){const saved=sourceDrafts.get(source);while(saved.firstChild)box.append(saved.firstChild);return}
  if(source!=='acme'){
   box.innerHTML=`<section class="cert-section"><h3>${source==='path'?'从服务器读取':'上传已有证书'}</h3><p class="cert-field-hint">证书需覆盖 ${esc(d.baseDomain)} 或其子域名。系统会校验证书、私钥和有效期，失败时保留当前证书。</p>${source==='path'?`<label>证书链绝对路径<input name="certificatePath" required placeholder="/data/certs/fullchain.pem" value="${esc(c.certificatePath||'')}"></label><label>私钥绝对路径<input name="privateKeyPath" required placeholder="/data/certs/privkey.pem" value="${esc(c.privateKeyPath||'')}"></label><p class="cert-field-hint">Docker 部署填写容器内路径，并先挂载证书目录。文件更新后点击“重新读取”安装；不会自动向颁发机构续期。</p>`:'<div class="cert-upload-grid"><label>证书链文件<input type="file" name="certificate" accept=".pem,.crt,.cer" required><small>PEM 格式，建议上传 fullchain</small></label><label>未加密私钥文件<input type="file" name="privateKey" accept=".key,.pem" required><small>必须与证书匹配；不支持 PFX / P12</small></label></div><p class="cert-field-hint">上传证书需自行续期，再上传新文件；安装后无需重启服务。</p>'}</section>`;return;
  }
  box.innerHTML=`<section class="cert-section"><h3>覆盖域名</h3><div class="cert-scope-grid"><label><input type="checkbox" data-name-root>主域名 <code>${esc(d.baseDomain)}</code></label><label><input type="checkbox" data-name-wild>泛域名 <code>*.${esc(d.baseDomain)}</code></label></div><div class="cert-name-preview" data-name-preview></div><details class="cert-custom-names"><summary>自定义覆盖域名</summary><label>每行一个域名<textarea name="names" rows="3">${esc((c.names?.length?c.names:[d.baseDomain,'*.'+d.baseDomain]).join('\n'))}</textarea></label><p class="cert-field-hint">只填此域名或其子域名，不带协议、端口或路径；泛域名仅覆盖下一层。</p></details></section><section class="cert-section"><h3>申请与 DNS 验证</h3><div class="cert-grid"><label>证书颁发机构<select name="ca"><option value="letsencrypt">Let's Encrypt · 免费</option><option value="zerossl">ZeroSSL · 需要 EAB</option></select></label><label>DNS 解析平台<select name="provider">${Object.entries(providerInfo).filter(([key])=>key!=='manual').map(([key,p])=>`<option value="${key}">${esc(p.name)}</option>`).join('')}</select></label></div><div id="dnsCredentialFields"></div><div id="eabFields"></div><label>联系邮箱<input name="email" type="email" required value="${esc(c.email||'')}" placeholder="you@example.com" autocomplete="email"></label><p class="cert-field-hint">用于 ACME 账户注册。DNS 验证不要求开放 80 端口。</p></section><details class="cert-section cert-settings"><summary>自动续期与高级设置 <span>提前 ${Number(c.renewBeforeDays)||30} 天</span></summary><label class="check"><input name="autoRenew" type="checkbox" ${(c.configured?c.autoRenew:true)?'checked':''}> 到期前自动续期</label>${certificateRenewalFields(c)}<label>密钥算法<select name="keyType"><option value="2048">RSA 2048（默认）</option><option value="4096">RSA 4096</option><option value="P256">ECDSA P-256</option></select></label></details><label class="check cert-terms"><input name="termsAccepted" type="checkbox" required ${c.termsAccepted?'checked':''}> 我已阅读并同意 <a id="caTerms" target="_blank" rel="noopener">证书颁发机构服务条款 ↗</a></label>`;
  form.elements.ca.value=c.ca||'letsencrypt';form.elements.provider.value=c.provider||(d.dnsProvider==='manual'?'alidns':d.dnsProvider)||'alidns';form.elements.keyType.value=c.keyType||'2048';
  function syncScopes(){const names=certificateNames(form.elements.names.value);box.querySelector('[data-name-root]').checked=names.includes(d.baseDomain);box.querySelector('[data-name-wild]').checked=names.includes('*.'+d.baseDomain);box.querySelector('[data-name-preview]').innerHTML=names.length?`<span>将申请</span>${names.map(n=>`<code>${esc(n)}</code>`).join('')}`:'<span class="dc-error">请至少选择或填写一个域名</span>'}
  box.querySelectorAll('[data-name-root],[data-name-wild]').forEach(b=>b.onchange=()=>{const extra=certificateNames(form.elements.names.value).filter(v=>v!==d.baseDomain&&v!=='*.'+d.baseDomain);form.elements.names.value=[...(box.querySelector('[data-name-root]').checked?[d.baseDomain]:[]),...(box.querySelector('[data-name-wild]').checked?['*.'+d.baseDomain]:[]),...extra].join('\n');syncScopes()});form.elements.names.oninput=syncScopes;syncScopes();
  // Detached nodes retain the draft credentials when switching providers or sources.
  const dnsDrafts=new Map();let activeProvider='';
  function dns(){const host=box.querySelector('#dnsCredentialFields'),key=form.elements.provider.value,p=providerInfo[key];if(activeProvider){const saved=document.createElement('div');while(host.firstChild)saved.append(host.firstChild);dnsDrafts.set(activeProvider,saved)}activeProvider=key;
   if(dnsDrafts.has(key)){const saved=dnsDrafts.get(key);while(saved.firstChild)host.append(saved.firstChild);return}
   const saved=c.credentialsConfigured&&c.provider===key;
   host.innerHTML=`<p class="cert-field-hint cert-provider-hint">${esc(p.hint)}${saved?' 已保存凭据，留空继续使用。':''}</p><div class="cert-grid"><label>${esc(p.one)}<input name="accessKey" type="password" autocomplete="new-password" ${saved?'':'required'} placeholder="${saved?'留空继续使用':'填写 DNS 授权'}"></label>${p.two?`<label>${esc(p.two)}<input name="secretKey" type="password" autocomplete="new-password" ${key==='alidns'&&!saved?'required':''} placeholder="${saved?'留空继续使用':''}"></label>`:''}</div>`;
  }
  let eabDraft=null,previousCA=form.elements.ca.value;
  function ca(){const zero=form.elements.ca.value==='zerossl',host=box.querySelector('#eabFields');if(form.elements.ca.value!==previousCA)form.elements.termsAccepted.checked=false;previousCA=form.elements.ca.value;
   box.querySelector('#caTerms').href=zero?'https://zerossl.com/terms/':'https://letsencrypt.org/repository/';
   if(!zero){if(host.firstChild){eabDraft=document.createElement('div');while(host.firstChild)eabDraft.append(host.firstChild)}return}
   if(eabDraft){while(eabDraft.firstChild)host.append(eabDraft.firstChild);return}
   const saved=c.ca==='zerossl'&&c.eabConfigured;
   host.innerHTML=`<div class="cert-eab"><b>ZeroSSL · 账户绑定</b><p class="cert-field-hint">在 ZeroSSL 账户中生成 EAB；它与上面的 DNS 授权不同。</p><div class="cert-grid"><label>EAB Key ID<input name="eabKeyId" type="password" autocomplete="new-password" ${saved?'':'required'} placeholder="${saved?'已保存，留空继续使用':''}"></label><label>EAB HMAC Key<input name="eabHmac" type="password" autocomplete="new-password" ${saved?'':'required'} placeholder="${saved?'已保存，留空继续使用':''}"></label></div></div>`;
  }
  form.elements.provider.onchange=dns;form.elements.ca.onchange=ca;dns();ca();
 }
 const source=requestedSource||(c.pendingACME?'acme':c.source==='path'?'path':c.source==='upload'?'upload':'acme');sourceFields(source);form.elements.source.value=source;
 form.onsubmit=async e=>{
  e.preventDefault();if(submitting)return;const f=new FormData(form),source=f.get('source'),saveOnly=e.submitter?.id==='certificateSaveOnly',error=dialog.querySelector('#certificateError'),progress=dialog.querySelector('#certificateProgress');
  submitting=true;error.textContent='';progress.textContent='正在校验并保存…';
  const controls=[...form.querySelectorAll('input,select,textarea,button')],disabled=controls.map(el=>el.disabled);controls.forEach(el=>el.disabled=true);
  try{
   if(source==='acme'){
    const names=certificateNames(f.get('names'));if(!names.length)throw Error('至少选择或填写一个域名');
    c=await api(certificatePath(d),'POST',{action:'configure',names,provider:f.get('provider'),ca:f.get('ca'),keyType:f.get('keyType'),email:f.get('email'),accessKey:f.get('accessKey'),secretKey:f.get('secretKey')||'',eabKeyId:f.get('eabKeyId')||'',eabHmac:f.get('eabHmac')||'',autoRenew:f.has('autoRenew'),renewBeforeDays:Number(f.get('renewBeforeDays')),retryHours:Number(f.get('retryHours')),termsAccepted:f.has('termsAccepted')});
    if(!saveOnly){await api(certificatePath(d),'POST',{action:'issue'});toast('申请已启动，结果会自动更新')}else toast('配置已保存，尚未发起申请');
   }else if(source==='path'){await api(certificatePath(d),'POST',{action:'path',certificatePath:f.get('certificatePath'),privateKeyPath:f.get('privateKeyPath')});toast('证书已读取并安装')}
   else{if(f.get('certificate').size+f.get('privateKey').size>180*1024)throw Error('证书链与私钥合计不能超过 180 KiB');await api(certificatePath(d),'POST',{action:'upload',certificate:await f.get('certificate').text(),privateKey:await f.get('privateKey').text()});toast('证书已校验并安装')}
   domainPanels.set(d.id,'certificate');dialog.close();dialog.replaceChildren();await renderCertificates(d);
  }catch(err){error.textContent=err.message;progress.textContent='请检查上方提示后重试';domainCertificates.set(d.id,c);drawDomainList()}
  finally{submitting=false;controls.forEach((el,i)=>el.disabled=disabled[i])}
 };
 if(!dialog.open)dialog.showModal();
}
