const providerInfo={manual:{name:'其他平台 / 手动管理'},alidns:{name:'阿里云 DNS',one:'AccessKey ID',two:'AccessKey Secret',hint:'填写有权修改该域名 TXT 记录的 RAM 凭据。'},dnspod:{name:'腾讯云 DNSPod',one:'DNSPod ID,Token',hint:'填写 DNSPod API 的 ID,Token 组合，不是腾讯云 SecretId。'},cloudflare:{name:'Cloudflare',one:'DNS API Token',two:'Zone API Token（可留空）',hint:'Token 需要该域名的 Zone:Read 和 DNS:Edit 权限，不使用 Global API Key。'}};
function certificatePath(d){return 'certificates?domainId='+encodeURIComponent(d.id)}
function certDate(v){return v&&!v.startsWith('0001')?new Date(v).toLocaleString():'—'}
async function renderCertificates(d){await loadDomainCertificate(d)}
function openCertificateEditor(d,c={},requestedSource){
 const sourceDrafts=new Map();let activeSource='';let dialog=document.getElementById('certDialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='certDialog';dialog.className='cert-dialog';document.body.append(dialog)}
 dialog.innerHTML=`<form id="certificateEditor"><header class="cert-dialog-head"><div><span class="eyebrow">${esc(d.baseDomain)}</span><h2>${c.installed?'管理证书':'添加证书'}</h2><p>选择证书来源，验证成功后用于当前域名的 HTTPS 入口</p></div><button type="button" class="icon-button" aria-label="关闭证书窗口">×</button></header><div class="cert-dialog-body"><div class="source-choices"><label><input type="radio" name="source" value="acme" checked><b>自动申请</b><span>ACME 签发与续期</span></label><label><input type="radio" name="source" value="upload"><b>上传证书</b><span>已有证书和私钥</span></label><label><input type="radio" name="source" value="path"><b>服务器路径</b><span>读取服务端文件</span></label></div><div id="certificateSourceFields"></div><details class="cert-help"><summary>第一次配置？查看填写说明</summary><p>DNS 平台指当前负责域名解析的平台，不一定是购买域名的平台。自动申请会创建临时 TXT 验证记录并在验证结束后清理，不会创建网站的 A 记录。</p><p>*.${esc(d.baseDomain)} 覆盖 router.${esc(d.baseDomain)}，不覆盖 a.router.${esc(d.baseDomain)}。签发后仍需配置解析、HTTPS 监听和端口。</p><p>密钥算法可用默认 RSA 2048。ZeroSSL 的 EAB 是证书账户凭据，与 DNS Token 不同。</p></details><p id="certificateError" class="cert-form-error" role="alert"></p></div><footer class="cert-dialog-foot"><span id="certificateProgress" role="status">配置保存在你的服务器</span><button type="button" data-cert-cancel>取消</button><button type="submit" id="certificateSaveOnly" value="save">保存配置</button><button type="submit" class="primary" id="certificateSubmit">保存并申请</button></footer></form>`;
 dialog.querySelector('.icon-button').onclick=()=>dialog.close();dialog.querySelector('[data-cert-cancel]').onclick=()=>dialog.close();const form=dialog.querySelector('form');
 form.querySelectorAll('[name=source]').forEach(r=>r.onchange=()=>sourceFields(r.value));
 function sourceFields(source){
  const sourceBox=dialog.querySelector('#certificateSourceFields');if(activeSource){const saved=document.createElement('div');while(sourceBox.firstChild)saved.append(sourceBox.firstChild);sourceDrafts.set(activeSource,saved)}activeSource=source;
  const box=dialog.querySelector('#certificateSourceFields');dialog.querySelector('#certificateSaveOnly').hidden=source!=='acme';dialog.querySelector('#certificateError').textContent='';dialog.querySelector('#certificateSubmit').textContent=source==='acme'?'保存并申请':source==='path'?'读取并安装':'校验并安装';
  if(sourceDrafts.has(source)){const saved=sourceDrafts.get(source);while(saved.firstChild)box.append(saved.firstChild);return}
  if(source!=='acme'){box.innerHTML=`<section class="cert-section"><h3>${source==='path'?'从服务器读取':'上传已有证书'}</h3><p>证书需覆盖 ${esc(d.baseDomain)} 或其子域名，校验成功后替换当前证书。</p>${source==='path'?`<label>证书链绝对路径<input name="certificatePath" required placeholder="/etc/ssl/fullchain.pem" value="${esc(c.certificatePath||'')}"></label><label>私钥绝对路径<input name="privateKeyPath" required placeholder="/etc/ssl/private/privkey.pem" value="${esc(c.privateKeyPath||'')}"></label><p class="muted">填写服务端文件路径；文件更新后需重新读取安装。</p>`:'<label>证书链（PEM / CRT）<input type="file" name="certificate" accept=".pem,.crt,.cer" required></label><label>未加密私钥（KEY / PEM）<input type="file" name="privateKey" accept=".key,.pem" required></label>'}</section>`;return}
  box.innerHTML=`<section class="cert-section"><h3><i>1</i> 证书覆盖哪些域名</h3><div class="cert-scope-grid"><label><input type="checkbox" data-name-root>主域名 <code>${esc(d.baseDomain)}</code></label><label><input type="checkbox" data-name-wild>泛域名 <code>*.${esc(d.baseDomain)}</code></label></div><details><summary>查看或编辑完整域名列表</summary><label>每行一个域名<textarea name="names" rows="3">${esc((c.names?.length?c.names:[d.baseDomain,'*.'+d.baseDomain]).join('\n'))}</textarea></label></details><p class="cert-scope-description">默认主域名 + 泛域名，覆盖 ${esc(d.baseDomain)} 和 router.${esc(d.baseDomain)} 等一级子域名。更多层级请展开域名列表填写。</p></section><section class="cert-section"><h3><i>2</i> 选择证书与 DNS 平台</h3><div class="cert-grid"><label>证书颁发机构<select name="ca"><option value="letsencrypt">Let's Encrypt · 免费 ACME</option><option value="zerossl">ZeroSSL · 需 EAB 凭据</option></select></label><label>DNS 验证平台<select name="provider">${Object.entries(providerInfo).filter(([key])=>key!=='manual').map(([key,p])=>`<option value="${key}">${esc(p.name)}</option>`).join('')}</select></label></div><div id="dnsCredentialFields"></div><div id="eabFields"></div><label>联系邮箱<input name="email" type="email" required value="${esc(c.email||'')}" placeholder="you@example.com"></label></section><details class="cert-section"><summary>续期与高级设置</summary><label>密钥算法<select name="keyType"><option value="2048">RSA 2048（默认）</option><option value="4096">RSA 4096</option><option value="P256">ECDSA P-256</option></select></label><label class="check"><input name="autoRenew" type="checkbox" ${c.autoRenew||!c.installed?'checked':''}> 到期前自动续期</label><p class="muted">每小时检查，剩余不足 30 天时续期。失败后保留旧证书，间隔 12 小时重试。</p></details><label class="check"><input name="termsAccepted" type="checkbox" required ${c.termsAccepted?'checked':''}> 我已阅读并同意 <a id="caTerms" target="_blank" rel="noopener">证书颁发机构服务条款</a></label>`;
  form.elements.ca.value=c.ca||'letsencrypt';form.elements.provider.value=c.provider||(d.dnsProvider==='manual'?'alidns':d.dnsProvider);form.elements.keyType.value=c.keyType||'2048';
  function syncScopes(){const n=form.elements.names.value.split(/[\n,，]+/).map(v=>v.trim());box.querySelector('[data-name-root]').checked=n.includes(d.baseDomain);box.querySelector('[data-name-wild]').checked=n.includes('*.'+d.baseDomain)}
  box.querySelectorAll('[data-name-root],[data-name-wild]').forEach(b=>b.onchange=()=>{const extra=form.elements.names.value.split(/[\n,，]+/).map(v=>v.trim()).filter(v=>v&&v!==d.baseDomain&&v!=='*.'+d.baseDomain);form.elements.names.value=[...(box.querySelector('[data-name-root]').checked?[d.baseDomain]:[]),...(box.querySelector('[data-name-wild]').checked?['*.'+d.baseDomain]:[]),...extra].join('\n')});form.elements.names.oninput=syncScopes;syncScopes();

  function dns(){const p=providerInfo[form.elements.provider.value],saved=c.credentialsConfigured&&c.provider===form.elements.provider.value;dialog.querySelector('#dnsCredentialFields').innerHTML=`<p class="cert-tip">${esc(p.hint)}</p><div class="cert-grid"><label>${esc(p.one)}<input name="accessKey" type="password" autocomplete="new-password" placeholder="${saved?'已保存，留空继续使用':'填写 DNS 凭据'}"></label>${p.two?`<label>${esc(p.two)}<input name="secretKey" type="password" autocomplete="new-password" placeholder="${saved?'已保存，留空继续使用':''}"></label>`:''}</div>`}
  function ca(){const zero=form.elements.ca.value==='zerossl';if(form.elements.ca.value!==c.ca)form.elements.termsAccepted.checked=false;dialog.querySelector('#caTerms').href=zero?'https://zerossl.com/terms/':'https://letsencrypt.org/repository/';dialog.querySelector('#eabFields').innerHTML=zero?`<div class="cert-tip"><b>ZeroSSL 账户绑定</b><p>到 ZeroSSL 账户生成 EAB 凭据，与 DNS Token 分开填写。</p><div class="cert-grid"><label>EAB Key ID<input name="eabKeyId" type="password" placeholder="${c.ca==='zerossl'&&c.eabConfigured?'已保存，留空继续使用':''}"></label><label>EAB HMAC Key<input name="eabHmac" type="password" placeholder="${c.ca==='zerossl'&&c.eabConfigured?'已保存，留空继续使用':''}"></label></div></div>`:''}
  form.elements.provider.onchange=dns;form.elements.ca.onchange=ca;dns();ca();
 }
 const source=requestedSource||(c.source==='path'?'path':c.source==='upload'?'upload':'acme');sourceFields(source);form.elements.source.value=source;
 let submitting=false;form.onsubmit=async e=>{e.preventDefault();if(submitting)return;submitting=true;const f=new FormData(form),source=f.get('source'),button=dialog.querySelector('#certificateSubmit'),error=dialog.querySelector('#certificateError'),progress=dialog.querySelector('#certificateProgress');error.textContent='';button.disabled=true;dialog.querySelector('#certificateSaveOnly').disabled=true;progress.textContent='正在校验并保存…';try{
  if(source==='acme'){const names=f.get('names').split(/[\n,，]+/).map(v=>v.trim()).filter(Boolean);if(!names.length)throw Error('至少填写一个域名');await api(certificatePath(d),'POST',{action:'configure',names,provider:f.get('provider'),ca:f.get('ca'),keyType:f.get('keyType'),email:f.get('email'),accessKey:f.get('accessKey'),secretKey:f.get('secretKey')||'',eabKeyId:f.get('eabKeyId')||'',eabHmac:f.get('eabHmac')||'',autoRenew:f.has('autoRenew'),termsAccepted:f.has('termsAccepted')});if(e.submitter?.id!=='certificateSaveOnly'){await api(certificatePath(d),'POST',{action:'issue'});toast('申请已启动，状态会自动更新')}else toast('配置已保存')}
  else if(source==='path'){await api(certificatePath(d),'POST',{action:'path',certificatePath:f.get('certificatePath'),privateKeyPath:f.get('privateKeyPath')});toast('证书已读取并安装')}
  else{if(f.get('certificate').size+f.get('privateKey').size>180*1024)throw Error('证书链与私钥文件合计不能超过 180 KiB');await api(certificatePath(d),'POST',{action:'upload',certificate:await f.get('certificate').text(),privateKey:await f.get('privateKey').text()});toast('证书已校验并安装')}
  domainPanels.set(d.id,'certificate');dialog.close();await renderCertificates(d);
 }catch(err){error.textContent=err.message;progress.textContent='请检查上方提示后重试'}finally{submitting=false;button.disabled=false;dialog.querySelector('#certificateSaveOnly').disabled=false}};
 if(!dialog.open)dialog.showModal();
}
