// Domain operations are grouped under their domain, with one compact row by default.
const domainCertificates=new Map(),domainPanels=new Map(),domainChecks=new Map(),domainCheckInputs=new Map(),domainPolls=new Map();
let domainSearch='',domainFilter='',domainGeneration=0,domainListPage=0;
const domainIcons={dns:'dns',certificate:'shield',history:'history'};
function domainMappings(d){return state.mappings.filter(m=>m.host===d.baseDomain||m.host.endsWith('.'+d.baseDomain))}
function domainHealth(c){if(!c)return {key:'loading',text:'读取中',tone:''};if(c.error)return {key:'attention',text:'读取失败',tone:'warn'};if(c.running)return {key:'running',text:'申请中',tone:'blue'};if(!c.installed)return {key:'attention',text:c.configured?'待申请':'未安装',tone:'quiet'};if(!c.certificate?.valid)return {key:'attention',text:'证书需更新',tone:'warn'};if(c.certificate.daysRemaining<(c.renewBeforeDays||30))return {key:'attention',text:'即将到期',tone:'warn'};return {key:'valid',text:'证书有效',tone:'green'}}
function rootPublicHealth(d,now=Date.now()){
 const r=d.publicHTTPS,port=Number(d.rootHTTPSPort)||443,managed=d.rootHTTPSProvider==='external';
 const endpoint=d.baseDomain+':'+port;
 if(!r||r.host!==d.baseDomain||Number(r.port)!==port)return {key:'attention',text:'公网待检测',tone:'quiet',detail:(managed?'宝塔 / 反向代理管理 · ':'')+endpoint};
 const checked=Date.parse(r.checkedAt),expires=Date.parse(r.expiresAt);
 if(!Number.isFinite(checked)||checked>now+60000||now-checked>24*3600000)return {key:'attention',text:'公网待复检',tone:'quiet',detail:'上次检测 '+certDate(r.checkedAt),result:r};
 if(r.valid&&Number.isFinite(expires)&&expires>now)return {key:'valid',text:'公网 HTTPS 已验证',tone:'green',detail:(managed?'宝塔 / 反代 · ':'')+port+' · 剩余 '+Math.floor((expires-now)/86400000)+' 天',result:r};
 return {key:'attention',text:r.valid?'公网证书已过期':'公网 HTTPS 异常',tone:'warn',detail:endpoint+' · 查看检测结果',result:r};
}
function certificateCoversHost(names,host){return (names||[]).some(name=>name===host||(name.startsWith('*.')&&host.endsWith(name.slice(1))&&host.split('.').length===name.split('.').length))}
function rootExternallyManaged(d,c={}){return d.rootHTTPSProvider==='external'}
function applyPublicHTTPSCheck(d,r){const row=(r.dns||[]).find(x=>x.host===d.baseDomain&&Number(x.port)===(Number(d.rootHTTPSPort)||443));if(row&&(row.certificate||row.error))d.publicHTTPS={...(row.certificate||{}),host:row.host,port:row.port,checkedAt:r.checkedAt,...(row.error?{valid:false,error:row.error}:{})}}
function publicHTTPSPanel(d){const h=rootPublicHealth(d),r=h.result;return `<div class="dc-public-https"><div class="dc-panel-heading"><div><h4>主域名 · 公网 HTTPS <span class="dc-badge ${h.tone}">${h.text}</span></h4><p>${d.rootHTTPSProvider==='external'?'宝塔 / 反向代理管理证书与续期':'证书以公网入口实际返回的结果为准'} · ${esc(d.baseDomain)}:${Number(d.rootHTTPSPort)||443}</p></div><button data-dc-source="${d.rootHTTPSProvider==='external'?'external':'acme'}">${d.rootHTTPSProvider==='external'?'管理外部入口':'管理系统证书'}</button></div>${r?`<p class="dc-help">上次检测：${certDate(r.checkedAt)}${r.valid?' · '+esc(r.issuer||'')+' · 到期 '+certDate(r.expiresAt):' · '+esc(r.error||'验证失败')}</p>`:''}<p class="dc-help">仅代表这个域名和端口。子域名映射需分别配置入口和证书；外部证书不会自动导入或由 RemoteGate 续期。</p><button data-dc-root-check>检测主域名 HTTPS</button></div>`}
function renderDomainCenter(){
 const generation=++domainGeneration;
 $('#content').classList.add('domain-center');
 $('#content').innerHTML=`<div class="dc-overview" id="domainOverview"></div><div class="dc-tools"><div class="dc-search"><span>${uiIcon('search')}</span><input id="domainSearch" placeholder="搜索域名或显示名称" aria-label="搜索域名或显示名称" value="${esc(domainSearch)}"></div><select id="domainFilter" aria-label="证书状态筛选"><option value="">全部域名</option><option value="valid">公网 HTTPS 已验证</option><option value="attention">公网待检测 / 更新</option><option value="running">申请中</option></select><button class="primary" id="addDomain">${uiIcon('plus')}添加域名</button></div><div id="domainList" class="dc-list"></div><details class="dc-guide"><summary>第一次接入域名？查看 3 个步骤 <span>解析 → 证书 → 访问</span></summary><div><p><b>01 · 指向服务器</b> 在负责 DNS 解析的平台添加 A / AAAA 记录，把访问域名指向服务器。</p><p><b>02 · 准备 HTTPS</b> 默认由系统申请与提供 HTTPS。主域名与泛域名可一起申请；已有外部入口时可自愿使用它。</p><p><b>03 · 配置访问入口</b> 放行公网 HTTPS 端口，确认映射的域名、协议和端口与入口一致。</p></div></details>`;
 $('#domainFilter').value=domainFilter;
 $('#domainSearch').oninput=e=>{domainSearch=e.target.value;domainListPage=0;drawDomainList()};
 $('#domainFilter').onchange=e=>{domainFilter=e.target.value;domainListPage=0;drawDomainList()};
 $('#addDomain').onclick=()=>openDomainEditor();
 drawDomainList();
 Promise.allSettled((state.domains||[]).map(async d=>{try{const c=await api(certificatePath(d));if(generation!==domainGeneration)return;domainCertificates.set(d.id,c);scheduleDomainPoll(d,c)}catch(e){if(generation===domainGeneration)domainCertificates.set(d.id,{error:e.message})}})).then(()=>{if(page==='domains'&&generation===domainGeneration)drawDomainList()});
}
function drawDomainList(){
 if(page!=='domains'||!$('#domainList'))return;
 const domains=state.domains||[],matches=domains.filter(d=>(d.baseDomain+' '+d.name).toLowerCase().includes(domainSearch.toLowerCase())&&(!domainFilter||(domainFilter==='running'?domainHealth(domainCertificates.get(d.id)).key==='running':rootPublicHealth(d).key===domainFilter)));
 const totalPages=Math.max(1,Math.ceil(matches.length/10));domainListPage=Math.min(domainListPage,totalPages-1);const visible=matches.slice(domainListPage*10,domainListPage*10+10);
 const valid=domains.filter(d=>rootPublicHealth(d).key==='valid').length,attention=domains.filter(d=>rootPublicHealth(d).key==='attention').length;
 $('#domainOverview').innerHTML=`<div><span>域名总数</span><strong>${domains.length}</strong></div><div><span><i class="dc-dot green"></i>公网 HTTPS 已验证</span><strong>${valid}</strong></div><div><span><i class="dc-dot warn"></i>待检测 / 更新</span><strong>${attention}</strong></div><p>一处管理解析、证书与续期<br><small>每个主域名独立配置</small></p>`;
 $('#domainList').innerHTML=visible.map(domainCenterRow).join('')||`<div class="dc-empty"><div>${uiIcon('globe')}</div><h3>${domains.length?'没有匹配的域名':'添加你的第一个域名'}</h3><p>${domains.length?'调整搜索或筛选条件。':'例如 example.com，随后为 router.example.com 配置 HTTPS 访问。'}</p>${domains.length?'':'<button class="primary" data-dc-empty>＋ 添加域名</button>'}</div>`;
 if(matches.length>10)$('#domainList').insertAdjacentHTML('beforeend',`<div class="dc-pagination"><span>共 ${matches.length} 个域名 · 第 ${domainListPage+1} / ${totalPages} 页</span><button data-dc-page="prev" ${domainListPage===0?'disabled':''}>上一页</button><button data-dc-page="next" ${domainListPage===totalPages-1?'disabled':''}>下一页</button></div>`);
 $('#domainList').querySelectorAll('[data-dc-page]').forEach(b=>b.onclick=()=>{domainListPage+=b.dataset.dcPage==='prev'?-1:1;drawDomainList()});
 $('#domainList').querySelector('[data-dc-empty]')?.addEventListener('click',()=>openDomainEditor());
 $('#domainList').querySelectorAll('[data-domain-panel]').forEach(b=>b.onclick=()=>{const id=b.dataset.domain,tab=b.dataset.domainPanel;domainPanels.set(id,domainPanels.get(id)===tab?'':tab);drawDomainList()});
 $('#domainList').querySelectorAll('[data-domain-edit]').forEach(b=>b.onclick=()=>openDomainEditor(domains.find(d=>d.id===b.dataset.domainEdit)));
 visible.forEach(d=>bindDomainPanel(d));
}
function domainCenterRow(d){
 const c=domainCertificates.get(d.id),h=rootPublicHealth(d),tab=domainPanels.get(d.id)||'',m=domainMappings(d),cert=c?.certificate;
 return `<article class="dc-domain"><div class="dc-row"><div class="dc-domain-mark" aria-hidden="true">${uiIcon('globe')}</div><div class="dc-domain-name"><h3>${esc(d.baseDomain)}</h3><span class="dc-domain-meta"><span>DNS：${esc((providerInfo[d.dnsProvider]||providerInfo.manual).name)}</span><span>显示名称：${esc(d.name||d.baseDomain)}</span></span></div><div class="dc-status"><span class="dc-badge ${h.tone}"><i></i>${h.text}</span><small>${esc(h.detail)}</small><small>内置证书：${esc(domainHealth(c).text)}</small></div><div class="dc-mapping-count"><strong>${m.length}</strong><span>个映射</span></div><div class="dc-row-actions">${['dns','certificate','history'].map(t=>`<button data-domain="${esc(d.id)}" data-domain-panel="${t}" class="${tab===t?'selected':''}" aria-expanded="${tab===t}" title="${t==='dns'?'解析接入':t==='certificate'?'HTTPS 证书':'任务记录'}">${uiIcon(domainIcons[t])} <span>${t==='dns'?'解析接入':t==='certificate'?'证书':'记录'}</span></button>`).join('')}<button class="dc-edit" data-domain-edit="${esc(d.id)}" title="编辑域名" aria-label="编辑域名">${uiIcon('edit')} <span>编辑</span></button></div></div>${tab?`<section class="dc-panel" id="domainPanel-${esc(d.id)}">${tab==='dns'?domainDNSPanel(d):tab==='history'?domainHistoryPanel(c):domainCertificatePanel(d,c)}</section>`:''}</article>`;
}
function domainDNSPanel(d){
 const m=domainMappings(d),check=domainChecks.get(d.id)||(d.publicHTTPS?{saved:true,checkedAt:d.publicHTTPS.checkedAt,dns:[{host:d.publicHTTPS.host,port:d.publicHTTPS.port,certificate:d.publicHTTPS}]}:null),draft=domainCheckInputs.get(d.id),type=d.serverIP?.includes(':')?'AAAA':'A';
 return `<div class="dc-panel-heading"><div><h4>域名解析与公网入口</h4><p>将访问地址指向服务器；DNS 授权用于申请证书时的 TXT 验证。</p></div><span class="dc-badge quiet">${esc((providerInfo[d.dnsProvider]||providerInfo.manual).name)}</span></div><div class="dc-dns-grid"><div><div class="dc-label">建议添加的解析 <small>在 DNS 平台操作</small></div><table class="dc-records"><thead><tr><th>主机记录</th><th>类型</th><th>记录值</th><th></th></tr></thead><tbody>${['@','*'].map(host=>`<tr><td><code>${host}</code><small>${host==='@'?'主域名':'一级子域名'}</small></td><td>${type}</td><td><code>${esc(d.serverIP||'请先填写公网 IP')}</code></td><td>${d.serverIP?`<button data-dc-copy="${esc(d.serverIP)}" title="复制记录值">${uiIcon('copy')}</button>`:''}</td></tr>`).join('')}</tbody></table><p class="dc-help">* 解析覆盖 router.${esc(d.baseDomain)}。具体子域名已有记录时，以其记录为准。Cloudflare 若开启代理，解析 IP 可能与服务器不同。</p></div><div class="dc-check-form"><div class="dc-label">检测实际访问入口</div><label>访问域名<input data-check-host value="${esc(draft?.host??d.baseDomain)}" list="checkHosts-${esc(d.id)}" placeholder="router.${esc(d.baseDomain)}"><datalist id="checkHosts-${esc(d.id)}">${m.map(x=>`<option value="${esc(x.host)}"></option>`).join('')}</datalist></label><label>公网 HTTPS 端口<input data-check-port type="number" min="1" max="65535" value="${esc(draft?.port??(d.rootHTTPSPort||443))}"></label><button class="primary" data-dc-check>检测解析与 HTTPS</button><p class="dc-help">检测 DNS 解析、服务器 IP 和公网证书。不会修改 DNS。可填写映射的真实公网端口。</p></div></div>${check?domainCheckResult(check):''}<details class="dc-advanced"><summary>域名管理</summary><p>已有映射时，需要先删除这些映射才能移除主域名。</p><button class="danger" data-dc-delete>删除此域名配置</button></details>`;
}
function domainCheckResult(r){if(r.error)return `<div class="dc-check-result warn" role="alert">${esc(r.error)}</div>`;return `<div class="dc-check-result" role="status"><div class="dc-label">检测结果 <small>${certDate(r.checkedAt)}${r.saved?' · 上次检测记录，重新检测可更新':''}</small></div>${(r.dns||[]).map(x=>`<div><b>${esc(x.host)}${x.certificate?':'+x.port:''}</b><span>${r.saved?'':x.error?esc(x.error):esc((x.addresses||[]).join('、'))}</span>${r.saved?'':`<span class="dc-badge ${x.error?'warn':x.matches?'green':'quiet'}">${x.error?'未解析':!r.serverIP?'未设置参考 IP':x.matches?'IP 匹配':'IP 不同'}</span>`}${x.certificate?`<p class="${x.certificate.valid?'dc-success':'dc-error'}">${x.certificate.valid?'HTTPS 验证通过 · '+esc(x.certificate.issuer)+' · 剩余 '+(Number.isFinite(Date.parse(x.certificate.expiresAt))?Math.floor((Date.parse(x.certificate.expiresAt)-Date.now())/86400000):x.certificate.daysRemaining)+' 天':'HTTPS 未通过：'+esc(x.certificate.error)}</p>`:''}</div>`).join('')}</div>`}
function certificateEntryNotice(c){
 if(!c.installed)return '';
 let title,detail,tone='quiet';
 if(c.httpsError){tone='warn';title='内置 HTTPS 启动失败';detail=c.httpsError+'。检查监听端口是否被占用。证书安装成功并不代表入口已启动。'}
 else if(!c.httpsAddress){tone='warn';title='证书已安装，HTTPS 入口未启用';detail='点击接入 HTTPS：默认由 RemoteGate 独立提供后台和映射 HTTPS；启用系统入口后，已安装证书自动加载，续期直接生效，无需导入其他软件。'}
 else if(c.httpsSettings?.mode==='shared'){title='共用 HTTPS 入口 '+c.httpsAddress;detail='映射使用系统证书，续期后新连接自动生效；其他域名转给宝塔，保留原证书。默认 443 的访问地址无需写端口。请分别检测映射与原有网站，监听成功不代表公网已验证。'}
 else{title='内置 HTTPS 监听 '+c.httpsAddress;detail='映射需访问实际公网端口，并放行服务器防火墙与安全组。通过宝塔 / Nginx 的其他入口访问时，以该入口配置的证书为准。监听已启动不代表公网已验证。'}
 return `<div class="dc-entry-notice ${tone}" role="status"><b>${esc(title)}</b><p>${esc(detail)}</p><button class="primary" data-dc-deploy>接入 HTTPS / 部署这张证书</button></div>`;
}
function domainCertificatePanel(d,c){
 if(!c)return '<p class="dc-help">正在读取证书…</p>';
 if(c.error)return `<p class="dc-error">${esc(c.error)}</p><button data-dc-refresh>重新读取</button>`;
 const cert=c.certificate,h=domainHealth(c),m=c.mappings||[],covered=m.filter(x=>x.covered).length;
 if(!c.installed&&!c.configured)return publicHTTPSPanel(d)+`<div class="dc-cert-empty"><div class="dc-cert-empty-icon" aria-hidden="true">${uiIcon('shield')}</div><div><h4>RemoteGate 内置证书</h4><p>用于系统独立的 HTTPS 服务；后台主域名和映射子域名都能使用。已选择外部入口的主域名无需重复申请。</p></div><button class="primary" data-dc-source="acme">${rootExternallyManaged(d,c)?'申请子域名证书':'申请免费证书'}</button><button data-dc-source="upload">上传证书</button><button data-dc-source="path">服务器路径</button></div>${certificateGuide(d)}`;
 const acme=c.source==='acme',disabled=c.running?'disabled':'',names=cert?.names||c.names||[],days=cert?.daysRemaining;
 const life=cert?Math.max(0,Math.min(100,100*(new Date(cert.expiresAt)-Date.now())/(new Date(cert.expiresAt)-new Date(cert.notBefore)))):0;
 return publicHTTPSPanel(d)+`<div class="dc-panel-heading dc-cert-heading"><div><h4>RemoteGate 内置证书 <span class="dc-badge ${h.tone}">${h.text}</span>${c.pendingACME?'<span class="dc-badge blue">新配置待申请</span>':''}</h4><p>${certificateSourceLabel(c.source)}${cert?' · '+esc(cert.issuer):' · 配置已保存，尚未签发'}</p></div><div class="dc-cert-actions"><button data-dc-config ${disabled}>证书配置</button><button class="primary" data-dc-issue ${disabled}>${c.running?'申请中…':c.pendingACME?'按新配置申请':acme&&c.installed?'立即续期':c.source==='path'?'重新读取':c.source==='upload'?'更新证书':'开始申请'}</button></div></div>
 <div class="dc-cert-summary"><div class="dc-cert-names"><small>当前覆盖域名</small><div>${names.map(n=>`<code>${esc(n)}</code>`).join(' ')}</div></div><div class="dc-cert-validity"><strong>${cert?(days<0?'已过期':days+' 天后到期'):'等待签发'}</strong><small>${cert?'到期 '+certDate(cert.expiresAt):'DNS 验证通过后安装'}</small>${cert?`<meter min="0" max="100" value="${life}" aria-label="证书剩余有效期比例">${Math.round(life)}%</meter>`:''}</div><div class="dc-cert-auto"><small>${acme?'自动续期':'更新方式'}</small>${acme?`<label class="dc-switch"><input type="checkbox" data-dc-renew ${c.autoRenew?'checked':''} ${disabled}><span>${c.autoRenew?'已开启':'已关闭'}</span></label><small>${c.pendingACME?'新配置申请成功后生效':c.autoRenew?'提前 '+(c.renewBeforeDays||30)+' 天':'按需手动续期'}</small>`:'<strong>手动更新</strong><small>到期前上传或重新读取</small>'}</div></div>
 ${certificateEntryNotice(c)}
 ${c.pendingACME&&c.installed?`<p class="dc-cert-pending">现有证书继续使用；新配置仅在申请成功后替换。待申请：${(c.names||[]).map(n=>`<code>${esc(n)}</code>`).join(' ')}</p>`:''}
 ${c.running||c.lastResult?.includes('失败')?`<p class="dc-cert-task ${c.running?'':'dc-error'}" role="status">${esc(c.lastResult)} <button data-dc-history>查看记录</button></p>`:''}
 ${acme&&c.installed?`<details class="dc-advanced"><summary>续期设置 <span>提前 ${c.renewBeforeDays||30} 天 · 失败后 ${c.retryHours||12} 小时重试</span></summary><form data-dc-renewal class="dc-renewal-form">${certificateRenewalFields(c)}<button type="submit" ${disabled}>保存续期设置</button><span data-renewal-result role="status"></span><p class="dc-help">${c.pendingACME?'新配置尚未申请，自动续期暂不执行。':c.autoRenew&&c.renewAfter?'最早续期时间：'+certDate(c.renewAfter)+'；随后每小时检查。':'自动续期已关闭，可在上方开启。'}</p></form></details>`:''}
 <details class="dc-advanced"><summary>证书详情与最近结果</summary><div class="dc-deployment"><p><b>来源</b>${certificateSourceLabel(c.source)}${acme?' · '+esc((providerInfo[c.provider]||providerInfo.manual).name):''}</p><p><b>有效期</b>${cert?certDate(cert.notBefore)+' → '+certDate(cert.expiresAt):'尚未签发'}</p><p><b>最近结果</b>${esc(c.lastResult||'暂无任务结果')}</p><p><b>最近尝试</b>${certDate(c.lastAttempt)}</p>${c.source==='path'?`<p><b>证书链路径</b><code>${esc(c.certificatePath)}</code></p><p><b>私钥路径</b><code>${esc(c.privateKeyPath)}</code></p>`:''}</div></details>
 <details class="dc-advanced"><summary>HTTPS 入口与映射覆盖 <span>${covered} / ${m.length} 已覆盖</span></summary><div class="dc-deployment"><p><b>${c.httpsError?'监听异常':c.httpsAddress?'内置 HTTPS 监听 '+esc(c.httpsAddress):'内置 HTTPS 未启用'}</b></p><p>${c.httpsError?esc(c.httpsError):'证书就绪后，还需配置 DNS 解析并放行 HTTPS 端口。宝塔 / Nginx 终止 TLS 时，需在代理上配置证书。'}</p>${m.map(x=>`<p><code>${esc(x.host)}</code><span class="dc-badge ${x.covered?'green':'warn'}">${x.covered?'证书覆盖':'未覆盖'}</span></p>`).join('')||'<p>此域名下暂无映射。</p>'}</div></details>
 <div class="dc-cert-bottom"><button data-dc-refresh>刷新状态</button>${c.installed?'<button data-dc-export>导出证书链</button>':''}<span>DNS 凭据不返回；完整部署包需验证管理员密码</span></div>`;
}
function domainHistoryPanel(c){const history=[...(c?.history||[])].reverse();return `<div class="dc-panel-heading"><div><h4>证书任务记录</h4><p>保留最近 30 条申请、导入和续期设置记录。</p></div><button data-dc-refresh>刷新记录</button></div>${history.length?`<div class="dc-history">${history.map(e=>`<div><i class="dc-dot ${e.status==='success'?'green':e.status==='error'?'warn':'blue'}"></i><div><b>${esc(e.action)}</b><time>${certDate(e.time)}</time><p>${esc(e.message)}</p></div></div>`).join('')}</div>`:`<p class="dc-help">暂无任务记录。${c?.lastResult?'升级前的最近结果：'+esc(c.lastResult):'申请或导入证书后会在这里显示结果。'}</p>`}`}
function bindDomainPanel(d){
 const node=document.getElementById('domainPanel-'+d.id);if(!node)return;
 const c=domainCertificates.get(d.id)||{};
 node.querySelectorAll('[data-dc-source]').forEach(b=>b.onclick=()=>openCertificateEditor(d,c,b.dataset.dcSource));
 node.querySelector('[data-dc-deploy]')?.addEventListener('click',()=>openHTTPSDeployment(d,c));
 node.querySelector('[data-dc-config]')?.addEventListener('click',()=>openCertificateEditor(d,c));
 node.querySelector('[data-dc-refresh]')?.addEventListener('click',()=>loadDomainCertificate(d));
 node.querySelector('[data-dc-issue]')?.addEventListener('click',async e=>{if(c.source==='upload'&&!c.pendingACME)return openCertificateEditor(d,c,'upload');await domainOperation(d,e.currentTarget,{action:c.pendingACME?'issue':c.source==='path'?'reload':c.installed?'renew':'issue'})});
 node.querySelector('[data-dc-renew]')?.addEventListener('change',async e=>{const b=e.currentTarget,desired=b.checked;try{b.disabled=true;await api(certificatePath(d),'POST',{action:'renewal',autoRenew:desired});await loadDomainCertificate(d);toast(desired?'自动续期已开启':'自动续期已关闭')}catch(err){b.checked=!desired;toast(err.message)}finally{b.disabled=false}});
 node.querySelector('[data-dc-history]')?.addEventListener('click',()=>{domainPanels.set(d.id,'history');drawDomainList()});
 node.querySelector('[data-dc-renewal]')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button'),result=f.querySelector('[data-renewal-result]');b.disabled=true;result.textContent='正在保存…';try{const data=new FormData(f);await api(certificatePath(d),'POST',{action:'renewal',autoRenew:c.autoRenew,renewBeforeDays:Number(data.get('renewBeforeDays')),retryHours:Number(data.get('retryHours'))});await loadDomainCertificate(d);toast('续期设置已保存')}catch(err){result.textContent=err.message}finally{b.disabled=false}});
 node.querySelector('[data-dc-export]')?.addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;try{const r=await api(certificatePath(d),'POST',{action:'export'}),url=URL.createObjectURL(new Blob([r.certificate],{type:'application/x-pem-file'})),a=document.createElement('a');a.href=url;a.download=r.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(err){toast(err.message)}finally{b.disabled=false}});
 node.querySelectorAll('[data-dc-copy]').forEach(b=>b.onclick=()=>copyText(b.dataset.dcCopy,{button:b,source:b.closest('tr').querySelector('td:nth-child(3) code'),success:'记录值已复制'}));
 node.querySelectorAll('[data-check-host],[data-check-port]').forEach(input=>input.oninput=()=>domainCheckInputs.set(d.id,{host:node.querySelector('[data-check-host]').value,port:node.querySelector('[data-check-port]').value}));
 node.querySelector('[data-dc-check]')?.addEventListener('click',e=>runDomainCheck(d,node.querySelector('[data-check-host]').value.trim(),node.querySelector('[data-check-port]').value,e.currentTarget));
 node.querySelector('[data-dc-root-check]')?.addEventListener('click',e=>runDomainCheck(d,d.baseDomain,d.rootHTTPSPort||443,e.currentTarget));
 node.querySelector('[data-dc-delete]')?.addEventListener('click',async()=>{if(!confirm('删除 '+d.baseDomain+' 的域名配置？已有映射时不能删除。'))return;try{await api('domains/'+encodeURIComponent(d.id),'DELETE');domainCertificates.delete(d.id);domainPanels.delete(d.id);await refresh();toast('域名配置已删除')}catch(err){toast(err.message)}});
}
async function domainOperation(d,b,body){b.disabled=true;try{await api(certificatePath(d),'POST',body);await loadDomainCertificate(d);toast(body.action==='reload'?'证书已重新读取':'证书任务已启动')}catch(e){toast(e.message)}finally{b.disabled=false}}
async function loadDomainCertificate(d){try{const c=await api(certificatePath(d));domainCertificates.set(d.id,c);scheduleDomainPoll(d,c);drawDomainList()}catch(e){domainCertificates.set(d.id,{error:e.message});drawDomainList()}}
function scheduleDomainPoll(d,c){clearTimeout(domainPolls.get(d.id));if(c.running&&page==='domains')domainPolls.set(d.id,setTimeout(()=>{if(page==='domains')loadDomainCertificate(d)},3000))}

async function runDomainCheck(d,host,port,b){b.disabled=true;b.textContent='检测中…';try{const r=await api('domains/check?id='+encodeURIComponent(d.id)+'&host='+encodeURIComponent(host)+'&port='+encodeURIComponent(port),'POST');applyPublicHTTPSCheck(d,r);domainChecks.set(d.id,r)}catch(err){domainChecks.set(d.id,{error:err.message});toast(err.message==='Failed to fetch'?'检测请求未完成，请检查后台连接；宝塔强制 HTTPS 时请使用 HTTPS 后台重新登录。':err.message)}finally{drawDomainList()}}
