// Domain operations are grouped under their domain, with one compact row by default.
const domainCertificates=new Map(),domainPanels=new Map(),domainChecks=new Map(),domainCheckInputs=new Map(),domainPolls=new Map();
let domainSearch='',domainFilter='',domainGeneration=0,domainListPage=0;
const domainIcons={dns:'◎',certificate:'◇',history:'◷'};
function domainMappings(d){return state.mappings.filter(m=>m.host===d.baseDomain||m.host.endsWith('.'+d.baseDomain))}
function domainHealth(c){if(!c)return {key:'loading',text:'读取中',tone:''};if(c.error)return {key:'attention',text:'读取失败',tone:'warn'};if(c.running)return {key:'running',text:'申请中',tone:'blue'};if(!c.installed)return {key:'attention',text:c.configured?'待申请':'未配置证书',tone:'quiet'};if(!c.certificate?.valid)return {key:'attention',text:'证书需更新',tone:'warn'};if(c.certificate.daysRemaining<30)return {key:'attention',text:'即将到期',tone:'warn'};return {key:'valid',text:'证书有效',tone:'green'}}
function renderDomainCenter(){
 const generation=++domainGeneration;
 $('#content').classList.add('domain-center');
 $('#content').innerHTML=`<div class="dc-overview" id="domainOverview"></div><div class="dc-tools"><div class="dc-search"><span>⌕</span><input id="domainSearch" placeholder="搜索域名或备注名称" aria-label="搜索域名或备注名称" value="${esc(domainSearch)}"></div><select id="domainFilter" aria-label="证书状态筛选"><option value="">全部域名</option><option value="valid">证书有效</option><option value="attention">需要配置或更新</option><option value="running">申请中</option></select><button class="primary" id="addDomain">＋ 添加域名</button></div><div id="domainList" class="dc-list"></div><details class="dc-guide"><summary>第一次接入域名？查看 3 个步骤 <span>解析 → 证书 → 访问</span></summary><div><p><b>01 · 指向服务器</b> 在负责 DNS 解析的平台添加 A / AAAA 记录，把访问域名指向服务器。</p><p><b>02 · 准备 HTTPS</b> 选择免费 ACME 自动申请，或导入已有证书。泛域名通过 DNS 验证。</p><p><b>03 · 配置访问入口</b> 放行公网 HTTPS 端口，确认映射的域名、协议和端口与入口一致。</p></div></details>`;
 $('#domainFilter').value=domainFilter;
 $('#domainSearch').oninput=e=>{domainSearch=e.target.value;domainListPage=0;drawDomainList()};
 $('#domainFilter').onchange=e=>{domainFilter=e.target.value;domainListPage=0;drawDomainList()};
 $('#addDomain').onclick=()=>openDomainEditor();
 drawDomainList();
 Promise.allSettled((state.domains||[]).map(async d=>{try{const c=await api(certificatePath(d));if(generation!==domainGeneration)return;domainCertificates.set(d.id,c);scheduleDomainPoll(d,c)}catch(e){if(generation===domainGeneration)domainCertificates.set(d.id,{error:e.message})}})).then(()=>{if(page==='domains'&&generation===domainGeneration)drawDomainList()});
}
function drawDomainList(){
 if(page!=='domains'||!$('#domainList'))return;
 const domains=state.domains||[],matches=domains.filter(d=>(d.baseDomain+' '+d.name).toLowerCase().includes(domainSearch.toLowerCase())&&(!domainFilter||domainHealth(domainCertificates.get(d.id)).key===domainFilter));
 const totalPages=Math.max(1,Math.ceil(matches.length/10));domainListPage=Math.min(domainListPage,totalPages-1);const visible=matches.slice(domainListPage*10,domainListPage*10+10);
 const valid=domains.filter(d=>domainHealth(domainCertificates.get(d.id)).key==='valid').length,attention=domains.filter(d=>domainHealth(domainCertificates.get(d.id)).key==='attention').length;
 $('#domainOverview').innerHTML=`<div><span>域名总数</span><strong>${domains.length}</strong></div><div><span><i class="dc-dot green"></i>证书有效</span><strong>${valid}</strong></div><div><span><i class="dc-dot warn"></i>待配置 / 更新</span><strong>${attention}</strong></div><p>一处管理解析、证书与续期<br><small>每个主域名独立配置</small></p>`;
 $('#domainList').innerHTML=visible.map(domainCenterRow).join('')||`<div class="dc-empty"><div>◎</div><h3>${domains.length?'没有匹配的域名':'添加你的第一个域名'}</h3><p>${domains.length?'调整搜索或筛选条件。':'例如 fanke.xyz，随后为 router.fanke.xyz 配置 HTTPS 访问。'}</p>${domains.length?'':'<button class="primary" data-dc-empty>＋ 添加域名</button>'}</div>`;
 if(matches.length>10)$('#domainList').insertAdjacentHTML('beforeend',`<div class="dc-pagination"><span>共 ${matches.length} 个域名 · 第 ${domainListPage+1} / ${totalPages} 页</span><button data-dc-page="prev" ${domainListPage===0?'disabled':''}>上一页</button><button data-dc-page="next" ${domainListPage===totalPages-1?'disabled':''}>下一页</button></div>`);
 $('#domainList').querySelectorAll('[data-dc-page]').forEach(b=>b.onclick=()=>{domainListPage+=b.dataset.dcPage==='prev'?-1:1;drawDomainList()});
 $('#domainList').querySelector('[data-dc-empty]')?.addEventListener('click',()=>openDomainEditor());
 $('#domainList').querySelectorAll('[data-domain-panel]').forEach(b=>b.onclick=()=>{const id=b.dataset.domain,tab=b.dataset.domainPanel;domainPanels.set(id,domainPanels.get(id)===tab?'':tab);drawDomainList()});
 $('#domainList').querySelectorAll('[data-domain-edit]').forEach(b=>b.onclick=()=>openDomainEditor(domains.find(d=>d.id===b.dataset.domainEdit)));
 visible.forEach(d=>bindDomainPanel(d));
}
function domainCenterRow(d){
 const c=domainCertificates.get(d.id),h=domainHealth(c),tab=domainPanels.get(d.id)||'',m=domainMappings(d),cert=c?.certificate;
 return `<article class="dc-domain"><div class="dc-row"><div class="dc-domain-mark">◎</div><div class="dc-domain-name"><h3>${esc(d.baseDomain)}</h3><span>${esc(d.name!==d.baseDomain?d.name:(providerInfo[d.dnsProvider]||providerInfo.manual).name)}</span></div><div class="dc-status"><span class="dc-badge ${h.tone}"><i></i>${h.text}</span><small>${cert?'到期 '+new Date(cert.expiresAt).toLocaleDateString()+' · '+cert.daysRemaining+' 天':c?.configured?'申请配置已保存':'添加证书以启用 HTTPS'}</small></div><div class="dc-mapping-count"><strong>${m.length}</strong><span>个映射</span></div><div class="dc-row-actions">${['dns','certificate','history'].map(t=>`<button data-domain="${esc(d.id)}" data-domain-panel="${t}" class="${tab===t?'selected':''}" aria-expanded="${tab===t}" title="${t==='dns'?'解析接入':t==='certificate'?'HTTPS 证书':'任务记录'}">${domainIcons[t]} <span>${t==='dns'?'解析接入':t==='certificate'?'证书':'记录'}</span></button>`).join('')}<button class="dc-edit" data-domain-edit="${esc(d.id)}" title="编辑域名" aria-label="编辑域名">⚙</button></div></div>${tab?`<section class="dc-panel" id="domainPanel-${esc(d.id)}">${tab==='dns'?domainDNSPanel(d):tab==='history'?domainHistoryPanel(c):domainCertificatePanel(d,c)}</section>`:''}</article>`;
}
function domainDNSPanel(d){
 const m=domainMappings(d),check=domainChecks.get(d.id),draft=domainCheckInputs.get(d.id),type=d.serverIP?.includes(':')?'AAAA':'A';
 return `<div class="dc-panel-heading"><div><h4>域名解析与公网入口</h4><p>将访问地址指向服务器；DNS 授权用于申请证书时的 TXT 验证。</p></div><span class="dc-badge quiet">${esc((providerInfo[d.dnsProvider]||providerInfo.manual).name)}</span></div><div class="dc-dns-grid"><div><div class="dc-label">建议添加的解析 <small>在 DNS 平台操作</small></div><table class="dc-records"><thead><tr><th>主机记录</th><th>类型</th><th>记录值</th><th></th></tr></thead><tbody>${['@','*'].map(host=>`<tr><td><code>${host}</code><small>${host==='@'?'主域名':'一级子域名'}</small></td><td>${type}</td><td><code>${esc(d.serverIP||'请先填写公网 IP')}</code></td><td>${d.serverIP?`<button data-dc-copy="${esc(d.serverIP)}" title="复制记录值">⧉</button>`:''}</td></tr>`).join('')}</tbody></table><p class="dc-help">* 解析覆盖 router.${esc(d.baseDomain)}。具体子域名已有记录时，以其记录为准。Cloudflare 若开启代理，解析 IP 可能与服务器不同。</p></div><div class="dc-check-form"><div class="dc-label">检测实际访问入口</div><label>访问域名<input data-check-host value="${esc(draft?.host??(m.find(x=>x.enabled&&x.publicScheme==='https')?.host||m.find(x=>x.enabled)?.host||d.baseDomain))}" list="checkHosts-${esc(d.id)}" placeholder="router.${esc(d.baseDomain)}"><datalist id="checkHosts-${esc(d.id)}">${m.map(x=>`<option value="${esc(x.host)}"></option>`).join('')}</datalist></label><label>公网 HTTPS 端口<input data-check-port type="number" min="1" max="65535" value="${esc(draft?.port??(m.find(x=>x.enabled&&x.publicScheme==='https')?.publicPort||443))}"></label><button class="primary" data-dc-check>检测解析与 HTTPS</button><p class="dc-help">检测 DNS 解析、服务器 IP 和公网证书。不会修改 DNS。可填写映射的真实公网端口。</p></div></div>${check?domainCheckResult(check):''}<details class="dc-advanced"><summary>域名管理</summary><p>已有映射时，需要先删除这些映射才能移除主域名。</p><button class="danger" data-dc-delete>删除此域名配置</button></details>`;
}
function domainCheckResult(r){if(r.error)return `<div class="dc-check-result warn" role="alert">${esc(r.error)}</div>`;return `<div class="dc-check-result" role="status"><div class="dc-label">检测结果 <small>${certDate(r.checkedAt)}</small></div>${(r.dns||[]).map(x=>`<div><b>${esc(x.host)}${x.certificate?':'+x.port:''}</b><span>${x.error?esc(x.error):esc((x.addresses||[]).join('、'))}</span><span class="dc-badge ${x.error?'warn':x.matches?'green':'quiet'}">${x.error?'未解析':!r.serverIP?'未设置参考 IP':x.matches?'IP 匹配':'IP 不同'}</span>${x.certificate?`<p class="${x.certificate.valid?'dc-success':'dc-error'}">${x.certificate.valid?'HTTPS 验证通过 · '+esc(x.certificate.issuer)+' · 剩余 '+x.certificate.daysRemaining+' 天':'HTTPS 未通过：'+esc(x.certificate.error)}</p>`:''}</div>`).join('')}</div>`}
function domainCertificatePanel(d,c){
 if(!c)return '<p class="dc-help">正在读取证书…</p>';
 if(c.error)return `<p class="dc-error">${esc(c.error)}</p><button data-dc-refresh>重新读取</button>`;
 const cert=c.certificate,h=domainHealth(c),m=c.mappings||[],covered=m.filter(x=>x.covered).length;
 if(!c.installed&&!c.configured)return `<div class="dc-panel-heading"><div><h4>为 ${esc(d.baseDomain)} 启用 HTTPS</h4><p>选择一种证书来源。签发成功后，内置 HTTPS 会自动使用证书。</p></div><span class="dc-badge quiet">尚未配置</span></div><div class="dc-source-cards"><button data-dc-source="acme"><span class="dc-source-icon">↻</span><b>自动申请免费证书 <em>推荐</em></b><small>Let's Encrypt / ZeroSSL<br>DNS 验证，到期前自动续期</small><span>开始配置 →</span></button><button data-dc-source="upload"><span class="dc-source-icon">↑</span><b>上传已有证书</b><small>选择证书链和私钥文件<br>适用于云平台签发的证书</small><span>选择文件 →</span></button><button data-dc-source="path"><span class="dc-source-icon">⌁</span><b>从服务器读取</b><small>填写证书链和私钥路径<br>适用于已有证书管理工具</small><span>填写路径 →</span></button></div>`;
 return `<div class="dc-panel-heading"><div><h4>HTTPS 证书 <span class="dc-badge ${h.tone}">${h.text}</span></h4><p>${c.source==='acme'?'自动申请':c.source==='path'?'服务器文件':c.source==='upload'?'手动上传':'ACME 配置已保存'} · ${esc(cert?.issuer||'尚未签发')}</p></div><div class="dc-cert-actions"><button data-dc-config ${c.running?'disabled':''}>${c.installed?'更新 / 配置':'修改配置'}</button><button class="primary" data-dc-issue ${c.running?'disabled':''}>${c.running?'申请中…':c.source==='acme'&&c.installed?'立即续期':c.source==='path'?'重新读取':c.source==='upload'?'更新证书':'开始申请'}</button></div></div><div class="dc-certificate-facts"><div><span>覆盖域名</span><strong>${(cert?.names||c.names||[]).map(n=>`<code>${esc(n)}</code>`).join(' ')}</strong></div><div><span>有效期</span><strong>${cert?new Date(cert.expiresAt).toLocaleDateString():'等待签发'}</strong><small>${cert?cert.daysRemaining+' 天后到期':'DNS 验证完成后签发'}</small></div><div><span>自动续期</span>${c.source==='acme'?`<label class="dc-switch"><input type="checkbox" data-dc-renew ${c.autoRenew?'checked':''} ${c.running?'disabled':''}><span>${c.autoRenew?'已开启':'已关闭'}</span></label>`:`<strong>${c.installed?'手动更新':'申请成功后生效'}</strong>`}<small>${c.renewAfter?'最早续期 '+certDate(c.renewAfter):'导入证书需重新上传或读取'}</small></div></div><div class="dc-latest ${c.lastResult?.includes('失败')?'warn':''}" role="status"><span>${c.running?'◌':'◷'}</span><div>${esc(c.lastResult||'配置已保存，点击“开始申请”签发证书')}<small>最近尝试 ${certDate(c.lastAttempt)}</small></div></div><details class="dc-advanced"><summary>HTTPS 入口与映射覆盖 <span>${covered} / ${m.length} 已覆盖</span></summary><div class="dc-deployment"><p><b>${c.httpsError?'监听异常':c.httpsAddress?'内置 HTTPS 监听 '+esc(c.httpsAddress):'内置 HTTPS 未启用'}</b></p><p>${c.httpsError?esc(c.httpsError):'证书就绪后，仍需将公网域名解析到服务器并放行 HTTPS 端口。外部 Nginx / Caddy 终止 TLS 时，需要在代理上配置证书。'}</p>${m.map(x=>`<p><code>${esc(x.host)}</code><span class="dc-badge ${x.covered?'green':'warn'}">${x.covered?'证书覆盖':'未覆盖'}</span></p>`).join('')||'<p>此域名下暂无映射。</p>'}</div></details><div class="dc-cert-bottom"><button data-dc-refresh>刷新状态</button>${c.installed?'<button data-dc-export>导出证书链 .pem</button>':''}<span>私钥与 DNS 凭据不在页面展示</span></div>`;
}
function domainHistoryPanel(c){const history=[...(c?.history||[])].reverse();return `<div class="dc-panel-heading"><div><h4>证书任务记录</h4><p>保留最近 30 条申请、导入和续期设置记录。</p></div><button data-dc-refresh>刷新记录</button></div>${history.length?`<div class="dc-history">${history.map(e=>`<div><i class="dc-dot ${e.status==='success'?'green':e.status==='error'?'warn':'blue'}"></i><div><b>${esc(e.action)}</b><time>${certDate(e.time)}</time><p>${esc(e.message)}</p></div></div>`).join('')}</div>`:`<p class="dc-help">暂无任务记录。${c?.lastResult?'升级前的最近结果：'+esc(c.lastResult):'申请或导入证书后会在这里显示结果。'}</p>`}`}
function bindDomainPanel(d){
 const node=document.getElementById('domainPanel-'+d.id);if(!node)return;
 const c=domainCertificates.get(d.id)||{};
 node.querySelectorAll('[data-dc-source]').forEach(b=>b.onclick=()=>openCertificateEditor(d,c,b.dataset.dcSource));
 node.querySelector('[data-dc-config]')?.addEventListener('click',()=>openCertificateEditor(d,c));
 node.querySelector('[data-dc-refresh]')?.addEventListener('click',()=>loadDomainCertificate(d));
 node.querySelector('[data-dc-issue]')?.addEventListener('click',async e=>{if(c.source==='upload')return openCertificateEditor(d,c,'upload');await domainOperation(d,e.currentTarget,{action:c.source==='path'?'reload':c.installed?'renew':'issue'})});
 node.querySelector('[data-dc-renew]')?.addEventListener('change',async e=>{const b=e.currentTarget,desired=b.checked;try{b.disabled=true;await api(certificatePath(d),'POST',{action:'renewal',autoRenew:desired});await loadDomainCertificate(d);toast(desired?'自动续期已开启':'自动续期已关闭')}catch(err){b.checked=!desired;toast(err.message)}finally{b.disabled=false}});
 node.querySelector('[data-dc-export]')?.addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;try{const r=await api(certificatePath(d),'POST',{action:'export'}),url=URL.createObjectURL(new Blob([r.certificate],{type:'application/x-pem-file'})),a=document.createElement('a');a.href=url;a.download=r.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(err){toast(err.message)}finally{b.disabled=false}});
 node.querySelectorAll('[data-dc-copy]').forEach(b=>b.onclick=()=>navigator.clipboard.writeText(b.dataset.dcCopy).then(()=>toast('记录值已复制')).catch(()=>toast('请手动复制记录值')));
 node.querySelectorAll('[data-check-host],[data-check-port]').forEach(input=>input.oninput=()=>domainCheckInputs.set(d.id,{host:node.querySelector('[data-check-host]').value,port:node.querySelector('[data-check-port]').value}));
 node.querySelector('[data-dc-check]')?.addEventListener('click',async e=>{const b=e.currentTarget,host=node.querySelector('[data-check-host]').value.trim(),port=node.querySelector('[data-check-port]').value;b.disabled=true;b.textContent='检测中…';try{const r=await api('domains/check?id='+encodeURIComponent(d.id)+'&host='+encodeURIComponent(host)+'&port='+encodeURIComponent(port),'POST');domainChecks.set(d.id,r)}catch(err){domainChecks.set(d.id,{error:err.message})}finally{drawDomainList()}});
 node.querySelector('[data-dc-delete]')?.addEventListener('click',async()=>{if(!confirm('删除 '+d.baseDomain+' 的域名配置？已有映射时不能删除。'))return;try{await api('domains/'+encodeURIComponent(d.id),'DELETE');domainCertificates.delete(d.id);domainPanels.delete(d.id);await refresh();toast('域名配置已删除')}catch(err){toast(err.message)}});
}
async function domainOperation(d,b,body){b.disabled=true;try{await api(certificatePath(d),'POST',body);await loadDomainCertificate(d);toast(body.action==='reload'?'证书已重新读取':'证书任务已启动')}catch(e){toast(e.message)}finally{b.disabled=false}}
async function loadDomainCertificate(d){try{const c=await api(certificatePath(d));domainCertificates.set(d.id,c);scheduleDomainPoll(d,c);drawDomainList()}catch(e){domainCertificates.set(d.id,{error:e.message});drawDomainList()}}
function scheduleDomainPoll(d,c){clearTimeout(domainPolls.get(d.id));if(c.running&&page==='domains')domainPolls.set(d.id,setTimeout(()=>{if(page==='domains')loadDomainCertificate(d)},3000))}
