let installPoll,guide;
const pendingGuides=new Map();
function showInstallGuide(r){
 clearInterval(installPoll);pendingGuides.set(r.device.id,r);
 guide={r,step:1,mode:'ssh',server:location.hostname==='127.0.0.1'?'http://10.0.2.2:18088':location.origin,command:'',expires:'',checking:false};
 $('#modal').classList.add('setup-dialog');$('#modalTitle').textContent='连接你的设备';$('#formError').textContent='';$('#save').type='button';$('#cancel').textContent='关闭向导';$('#cancel').onclick=()=>$('#modal').close();
 renderGuide();if(!$('#modal').open)$('#modal').showModal();
}
function renderGuide(){
 const g=guide,step=g.step;
 $('#fields').innerHTML=`<p class="setup-subtitle">${esc(g.r.device.name)} · 首次连接成功后才会保存到设备列表。接入凭据 24 小时内有效，服务端重启后失效</p><div class="setup-progress"><span>步骤 ${step} / 3</span><span>${step===3?'设备已连接':step===2?'等待设备上线':'选择安装方式'}</span></div><div class="setup-track"><i style="width:${step/3*100}%"></i></div><div class="setup-stages"><span class="${step===1?'current':''}">01 安装客户端</span><span class="${step===2?'current':''}">02 检测上线</span><span class="${step===3?'current':''}">03 添加域名</span></div><div id="setupBody" class="setup-body"></div>`;
 $('#save').hidden=false;$('#save').disabled=false;$('#cancel').textContent=step===2?'返回安装步骤':'关闭向导';$('#cancel').onclick=()=>{if(step===2){clearInterval(installPoll);g.step=1;renderGuide()}else $('#modal').close()};
 if(step===1){
 $('#setupBody').innerHTML=`<h3>在路由器上安装 RemoteGate</h3><p class="muted">支持 iStoreOS / OpenWrt（opkg），x86_64、ARM64 和 ARMv7。</p><div class="setup-methods"><button type="button" data-method="ssh" class="${g.mode==='ssh'?'selected':''}"><b>${uiIcon('terminal')} SSH 一键安装</b><small>自动安装并填写连接配置</small></button><button type="button" data-method="manual" class="${g.mode==='manual'?'selected':''}"><b>${uiIcon('package')} iStore 手动安装</b><small>下载文件，在路由器后台上传</small></button></div><label>服务端地址<input id="installServer" type="url" value="${esc(g.server)}"></label><p class="setup-hint">本机虚拟机使用 http://10.0.2.2:18088；真实路由器请填写服务器域名或可访问的局域网地址。</p><section class="setup-panel" id="methodBody"></section><h3>常见问题</h3><details><summary>在哪里执行安装命令？</summary><p>在电脑终端执行 ssh root@路由器IP，输入路由器管理员密码，登录后粘贴命令。密码输入时不显示字符是正常的。</p></details><details><summary>安装后看不到设备怎么办？</summary><p>检查服务端地址、路由器联网和“服务 → RemoteGate”的启用状态，再查看系统日志中的 remotegate 信息。</p></details><details><summary>链接过期、下载失败怎么办？</summary><p>安装链接仅可下载一次，15 分钟后过期。重新生成命令即可重试；若系统提示 curl 不存在，可使用 iStore 手动安装。</p></details>`;
 $('#installServer').oninput=e=>{g.server=e.target.value;g.command='';const pre=$('#installCommand');if(pre)pre.textContent='地址已更改，请重新生成命令';const copy=$('#copyInstall');if(copy)copy.disabled=true};
 document.querySelectorAll('[data-method]').forEach(b=>b.onclick=()=>{g.mode=b.dataset.method;renderGuide()});
 if(g.mode==='ssh'){
 $('#methodBody').innerHTML=`<h3>复制命令，在路由器 SSH 中执行</h3><p>以 root 登录，确保已安装 curl。脚本会下载安装包、校验完整性、写入配置并启动服务。</p><div class="command-header"><span>安装命令</span><button type="button" id="copyInstall" ${g.command?'':'disabled'}>${uiIcon('copy')}复制</button></div><pre id="installCommand">${esc(g.command||'点击下方按钮，生成此设备的专属安装命令')}</pre><div class="command-footer"><button type="button" id="generateInstall">${g.command?'重新生成':'生成安装命令'}</button><small id="installExpiry">${esc(g.expires)}</small></div>`;
 $('#copyInstall').onclick=e=>copyText(g.command,{button:e.currentTarget,source:$('#installCommand')});
 $('#generateInstall').onclick=async()=>{const b=$('#generateInstall');b.disabled=true;$('#formError').textContent='';try{const result=await api('install','POST',{deviceId:g.r.device.id,token:g.r.token,server:g.server.trim()});g.command=result.command;g.expires='有效至 '+new Date(result.expiresAt).toLocaleTimeString()+' · 仅可下载一次';renderGuide()}catch(e){$('#formError').textContent=e.message}finally{b.disabled=false}};
 }else{
 $('#methodBody').innerHTML=`<h3>1. 下载安装包</h3><a class="package-link" href="/downloads/remotegate.run" download>${uiIcon('download')}下载 RemoteGate .run 安装包</a><h3>2. 上传安装</h3><p>路由器后台 → iStore → 手动安装 → 选择文件，等待安装完成。</p><h3>3. 填写连接配置</h3><p>进入“服务 → RemoteGate”，填写下列信息，启用后保存并应用。</p><pre id="manualConfig"></pre>`;
 $('#manualConfig').textContent='服务器：'+g.server+'\n设备 ID：'+g.r.device.id+'\n设备 Token：'+g.r.token;
 }
 $('#save').textContent='我已完成安装 →';$('#save').onclick=()=>{g.step=2;renderGuide();checkGuide();installPoll=setInterval(checkGuide,3000)};
 }else if(step===2){
 $('#setupBody').innerHTML=`<div class="setup-detection"><div class="detection-symbol">${uiIcon('refresh')}</div><h3>正在等待设备连接</h3><p id="detectMessage" role="status">每 3 秒自动检测一次，通常需要 10–30 秒。</p><button type="button" id="checkAgain">立即检测</button></div><div class="setup-panel"><h3>如果一直未上线，请确认</h3><ul><li>安装命令已经执行成功。</li><li>路由器可以访问填写的服务端地址。</li><li>“服务 → RemoteGate”已启用。</li><li>设备 ID 和 Token 正确，防火墙允许连接。</li></ul></div>`;
 $('#checkAgain').onclick=checkGuide;$('#save').hidden=true;
 }else{
 $('#setupBody').innerHTML=`<div class="setup-detection"><div class="detection-symbol success">${uiIcon('check')}</div><h3>设备已成功上线</h3><p>${esc(g.r.device.name)} 已连接到你的服务器。</p></div><div class="setup-panel"><h3>接下来，添加第一个域名</h3><p>例如将 router.example.com 映射到路由器的 http://127.0.0.1:80，即可通过该域名打开管理页面。</p></div>`;
 $('#save').textContent='添加域名 →';$('#save').onclick=()=>{expandedFeatures.set(g.r.device.id,'domains');$('#modal').close();openEditor('mapping',{deviceId:g.r.device.id})};
 }
}
async function checkGuide(){const g=guide;if(!g||g.step!==2||!$('#modal').open){clearInterval(installPoll);return}if(g.checking)return;g.checking=true;try{const s=await api('state');if(guide!==g||g.step!==2||!$('#modal').open)return;if(s.devices.some(d=>d.id===g.r.device.id&&d.online)){state=s;clearInterval(installPoll);g.step=3;renderGuide();render()}else $('#detectMessage').textContent='尚未连接 · 最近检测 '+new Date().toLocaleTimeString()}catch(e){if(guide===g&&g.step===2&&$('#detectMessage'))$('#detectMessage').textContent='检测失败：'+e.message}finally{g.checking=false}}
$('#modal').addEventListener('close',()=>{clearInterval(installPoll);$('#modal').classList.remove('setup-dialog')});

function renderPackages(){
 const p=state.package||{},m=p.manifest,b=p.server;
 $('#content').innerHTML=`<div class="toolbar"><div><h2>安装包与版本</h2><p class="muted">当前服务端、可下载的插件包，以及设备实际安装的版本</p></div>${p.available?`<a class="package-link" href="/downloads/remotegate.run" download>${uiIcon('download')}下载安装包</a>`:''}</div>${b?`<article class="card"><div class="toolbar"><h2>${uiIcon('dns')} RemoteGate v${esc(b.version)}</h2><a href="${esc(b.releaseURL)}" target="_blank" rel="noopener">版本说明与历史发布 ↗</a></div><p class="muted">构建提交：<code>${esc(b.commit==='development'?'本地开发构建':b.commit.slice(0,12))}</code> · 构建时间：${esc(b.builtAt==='unknown'?'未记录':new Date(b.builtAt).toLocaleString())}</p><details><summary>固定版本 Docker 镜像</summary><code>${esc(b.image)}</code><p class="muted">stable 跟随发布版本，固定标签用于指定版本部署。</p></details></article>`:''}<div class="steps"><article><b>${uiIcon('package')}${esc(p.name||'RemoteGate 安装包')}</b><p>${p.available?'已部署 · '+(p.size/1024/1024).toFixed(2)+' MB':'尚未部署安装包'}</p><p>插件包版本：${esc(m?.packageVersion||'未提供可验证的版本清单')}</p><p>客户端版本：${esc(m?.agentVersion||'未知')}</p><p>包名：${esc(m?.packageName||'未知')}</p></article><article><b>${uiIcon('monitor')}安装内容</b><p>${esc(m?.contents?.join('、')||'暂无内容清单')}</p><p>支持架构：${esc(m?.architectures?.join(' / ')||'未知')}</p><p>适用系统：iStoreOS / OpenWrt（使用 opkg）</p></article></div>${p.available?`<details><summary>文件校验 SHA-256</summary><pre style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(p.sha256)}</pre></details>`:''}<h2 style="margin-top:28px">${uiIcon('monitor')} 设备安装情况</h2><p class="muted">已上报的版本在离线后保留。旧客户端未上报插件版本时显示“未上报”，不推测安装状态。</p><table><thead><tr><th>设备</th><th>连接状态</th><th>客户端版本</th><th>插件包版本</th></tr></thead><tbody>${state.devices.map(d=>`<tr><td>${esc(d.name)}</td><td>${d.online?'在线':'离线'}</td><td>${esc(d.version||'尚未上报')}</td><td>${esc(d.packageVersion||'未上报')}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">暂无已连接设备</td></tr>'}</tbody></table>`;
}

function renderDomains(){renderDomainCenter()}
function openDomainEditor(d={},returnMapping=null){openEditor('domain',d);$('#modalTitle').textContent=d.id?'编辑域名':'添加域名';$('#fields').innerHTML=`<label>显示名称<input name="name" value="${esc(d.name||'')}" placeholder="例如 办公室域名" aria-describedby="domainNameHint"></label><p class="domain-name-hint" id="domainNameHint">可选，仅用于后台识别，不参与访问地址。留空时使用域名本身。</p><label>域名 / 后缀<input name="baseDomain" required placeholder="example.com" value="${esc(d.baseDomain||'')}"></label><label>服务器公网 IP<input name="serverIP" placeholder="可稍后填写" value="${esc(d.serverIP||'')}"></label><label>DNS 平台<select name="dnsProvider"><option value="manual">其他平台 / 手动管理</option><option value="alidns" ${d.dnsProvider==='alidns'?'selected':''}>阿里云 DNS</option><option value="dnspod" ${d.dnsProvider==='dnspod'?'selected':''}>腾讯云 DNSPod</option><option value="cloudflare" ${d.dnsProvider==='cloudflare'?'selected':''}>Cloudflare</option></select></label><p class="muted">可添加 example.com 或 gate.example.com 这类域名后缀。这里保存域名配置，不会自动创建 DNS 解析；DNS 平台请选择当前负责解析的平台。</p>`;editing={type:'domain',item:d,returnMapping};if(returnMapping){$('#cancel').textContent='返回映射';$('#cancel').onclick=()=>{$('#modal').close();openEditor('mapping',returnMapping)}}}

const originalEditorSubmit=$('#editor').onsubmit;
$('#editor').onsubmit=async e=>{if(editing?.type!=='domain')return originalEditorSubmit(e);e.preventDefault();$('#save').disabled=true;try{const f=new FormData(e.target),d=editing.item,draft=editing.returnMapping;const saved=await api('domains',d.id?'PUT':'POST',{id:d.id||'',name:f.get('name'),baseDomain:f.get('baseDomain'),serverIP:f.get('serverIP'),dnsProvider:f.get('dnsProvider')});$('#modal').close();await refresh();if(draft)openEditor('mapping',{...draft,_mappingDraft:{...draft._mappingDraft,domainSuffix:saved.baseDomain}});toast('域名配置已保存')}catch(x){$('#formError').textContent=x.message}finally{$('#save').disabled=false}};

// Complete mapping workbench: explicit public endpoint, copy/open actions and probe feedback.
const mappingProbeResults=new Map(),baseMappingAction=action;
mappingURL=value=>publicMappingURL(typeof value==='string'?{host:value}:value);
action=async(a,id)=>{if(a!=='probe')return baseMappingAction(a,id);const m=state.mappings.find(x=>x.id===id);if(!m)return;mappingProbeResults.set(id,{loading:true});deviceCards();try{const r=await api('probe','POST',{id});mappingProbeResults.set(id,{ok:r.status>=200&&r.status<500,text:`HTTP ${r.status} · ${r.latencyMs} ms`})}catch(e){mappingProbeResults.set(id,{ok:false,text:e.message})}deviceCards()};
deviceCards=()=>{
 const devices=state.devices.filter(d=>{const mappings=state.mappings.filter(m=>m.deviceId===d.id);return (!filter||d.online===(filter==='yes'))&&JSON.stringify([d.name,d.id,mappings]).toLowerCase().includes(query.toLowerCase())});
 $('#deviceCards').innerHTML=devices.map(d=>{const mappings=state.mappings.filter(m=>m.deviceId===d.id),enabled=mappings.filter(m=>m.enabled).length;return `<article class="device-card"><div class="device-head"><div class="device-icon" aria-hidden="true">${uiIcon('monitor')}</div><div class="device-info"><div class="device-title"><strong>${esc(d.name)}</strong><span class="pill ${d.online?'on':''}">${d.online?'在线':'离线'}</span></div><div class="device-meta"><span>ID：${esc(d.id)}</span><span>客户端版本：${esc(d.version||'尚未上报')}</span><span>${d.online?'连接于 '+esc(new Date(d.connectedAt).toLocaleString()):'等待设备连接'}</span></div></div><div class="actions"><button data-action="rename" data-id="${esc(d.id)}">${uiIcon('edit')}重命名</button></div></div><div class="device-tabs"><button type="button" class="feature-tab" data-feature="domains" data-device="${esc(d.id)}" aria-expanded="${expandedFeatures.get(d.id)==='domains'}" aria-controls="domains-${esc(d.id)}">${uiIcon('globe')}访问域名（${mappings.length}）<i aria-hidden="true"></i></button></div><div class="device-body" id="domains-${esc(d.id)}" ${expandedFeatures.get(d.id)==='domains'?'':'hidden'}><div class="toolbar"><div><h2>域名映射 <small class="muted">已启用 ${enabled} / ${mappings.length}</small></h2><p class="muted">一个访问域名对应一个设备内网 Web 服务</p></div><button class="primary" data-action="addMapping" data-id="${esc(d.id)}">${uiIcon('plus')}添加映射</button></div><div class="tablewrap"><table class="mapping-table"><thead><tr><th>公网访问地址</th><th>内网地址</th><th>备注与状态</th><th>操作</th></tr></thead><tbody>${mappings.map(m=>mappingRow(m,d)).join('')||'<tr><td colspan="4" class="empty">还没有域名映射，点击“添加映射”接入这台设备的内网服务。</td></tr>'}</tbody></table></div></div><details><summary>${uiIcon('settings')}设备管理</summary><button class="danger" data-action="deleteDevice" data-id="${esc(d.id)}">${uiIcon('trash')}删除设备</button></details></article>`}).join('')||'<div class="workbench-empty"><h2>暂无匹配设备</h2><p class="muted">添加一台路由器，即可在设备下管理它的域名和内网服务。</p></div>';
 $('#deviceCards').querySelectorAll('[data-feature]').forEach(b=>b.onclick=()=>toggleFeature(b.dataset.device,b.dataset.feature));
 $('#deviceCards').querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset.id).catch(e=>toast(e.message)));
 $('#deviceCards').querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyText(b.dataset.copy,{button:b,source:b.parentElement.querySelector('a,code')}));
};
function mappingRow(m,d){const endpoint=publicMappingURL(m),probe=mappingProbeResults.get(m.id);return `<tr><td><div class="mapping-address"><span class="mapping-dot ${m.enabled?'enabled':''}" title="${m.enabled?'已启用':'已停用'}"></span><a href="${esc(endpoint)}" title="${esc(endpoint)}" target="_blank" rel="noopener">${esc(endpoint)}</a><button type="button" data-copy="${esc(endpoint)}" title="复制公网地址" aria-label="复制公网地址">${uiIcon('copy')}</button></div></td><td><div class="mapping-address"><code title="${esc(m.target)}">${esc(m.target)}</code><button type="button" data-copy="${esc(m.target)}" title="复制内网地址" aria-label="复制内网地址">${uiIcon('copy')}</button></div></td><td><span class="mapping-note" title="${esc(m.note||'暂无备注')}">${esc(m.note||'—')}</span>${probe?`<span class="mapping-probe" title="${esc(probe.text||'检测中…')}">${probe.loading?'检测中…':esc(probe.text)}</span>`:''}</td><td><div class="actions mapping-actions"><a href="${esc(endpoint)}" target="_blank" rel="noopener" title="打开" aria-label="打开">${uiIcon('external')}</a><button data-action="edit" data-id="${esc(m.id)}" title="编辑" aria-label="编辑">${uiIcon('edit')}</button><button data-action="probe" data-id="${esc(m.id)}" title="检测" aria-label="检测">${uiIcon('activity')}</button><button data-action="toggle" data-id="${esc(m.id)}" title="${m.enabled?'停用':'启用'}" aria-label="${m.enabled?'停用':'启用'}">${uiIcon(m.enabled?'pause':'play')}</button><button class="danger" data-action="deleteMapping" data-id="${esc(m.id)}" title="删除" aria-label="删除">${uiIcon('trash')}</button></div></td></tr>`}
